mixed-port: 7890
allow-lan: false
mode: rule
log-level: silent

proxies:
  - name: "📵 账号已停用，无法连接"
    type: ss
    server: 192.0.2.1
    port: 1080
    cipher: aes-128-gcm
    password: expired

proxy-groups:
  - name: "🔴 你的账号已经到期！"
    type: select
    proxies:
      - "⚠️ 请联系管理员续费"

  - name: "⚠️ 请联系管理员续费"
    type: select
    proxies:
      - "📵 账号已停用，无法连接"

rules:
  - MATCH,REJECT
